build-emacs-for-macos

To make the emacs build script work with Ruby 2.5.1, I had to cast 3 File.dirname() objects to Pathname objects.

Fixing missing cast for Ruby 2.5.1.

---

.rubocop.yml
README.md
build-emacs-for-macos
launcher.bash.erb

The solution to get libgccjit properly working, and embedded in
Emacs.app included:
- The contents of GCC's lib folder (`/usr/local/opt/gcc/lib`) is copied
into the `Contents/MacOS/lib-<arch>-<os_version>` folder.
- Setting `LIBRARY_PATH` environment variable to correct GCC lib
folders within Emacs.app. This is done through a bash launcher script
which replaces the regular `Contents/MacOS/Emacs` executable. The main
Emacs executable itself is named `Emacs-bin` now instead, so anything
that depends on the exact process name will need updating.
- The launcher script also adds `Content/MacOS/bin` and
`Content/MacOS/libexec` folders to the PATH environment variable, to
so ensure binary tools packaged into Emacs itself are available. This
is done even when not doing a native-comp build. The …

feat(native_comp): embedd gcc/libgccjit into Emacs.app

---

build-emacs-for-macos
patches/native-comp-env-setup.patch

This incorporates @claford-v-lawrence's PR #25, with the addition of adding the Xcode CLI tools lib path to the runtime `LIBRARY_PATH` via the native-comp-env-setup patch.
I've fired off a build with these changes on Catalina from commit [bd693cc](https://github.com/emacs-mirror/emacs/commit/bd693ccea7ba4a6aafda103f7a9166f76363c86b) to confirm everything still works.
@AllenDang, @claford-v-lawrence would you two be able to test this on Big Sur, without the `(setenv "LIBRARY_PATH" ...` snippet in your config I posted on #25.
Confirmations:
- Catalina:
- Big Sur:

fix(big-sur): resolve issues with building and native-comp on Big Sur

---

build-emacs-for-macos
patches/native-comp-env-setup.diff.erb

The old patch would dynamically glob within Emacs.app/Contents/MacOS/lib/gcc
using the full absolute path to Emacs.app. If there are obsure characters like
"[]" and others in the absolute path, it can cause glob search within the
native-compile-setup-environment-variables function to fail, in turn preventing
native-comp from working.
The fix is to hard-code the relative paths from Emacs' invocation-directory
(\*\*/Emacs.app/Contents/MacOS) into the environment setup function itself,
making it very simple and effectively just joining a few strings and setting an
environment variable.
It did require a little bit of cleanup and better organization of the
GCC/libgccjit releated code in the build script, creating a new GccInfo class
which is the central place for determining various paths and …

fix(native_comp): improve env setup patch fixing potential issues

---

build-emacs-for-macos

This resolves #12, which it turns out was caused by the aggressive shared
library embedding and re-linking. Simply removing it fixes the issue, without
causing any issues I've been able to find. Despite the build now linking to more
dynamic libraries provided by macOS than it was before.
I will be looking into if it's possible to get more of those libs embedded, but
it looks like it involves re-installing various homebrew packages from source,
so they link against dependencies already installed via Homebrew, rather than
those available in macOS itself. But for now, this change seems perfectly good
and stable based on my testing.

fix(svg): fix SVG rendering crash and enable SVG support by default

---

README.md
build-emacs-for-macos
patches/native-comp-env-setup.diff.erb

This simply addresses a folder name within Emacs.app which was causing
`codesign` to throw a fatal error when trying to sign the application bundle.

feat(codesign): minor internal fix to output Emacs.app bundle for compatibility with codesign

---

README.md
build-emacs-for-macos
helper/emacs-cli.bash

This makes setting up a `emacs` terminal command that works with the
self-contained Emacs.app bundle much simpler, as you just need to add
`Emacs.app/Conents/MacOS/bin` to your `PATH`.
For example, if you place Emacs.app in `/Applications`, add this to your shell
setup:
```shell
if [ -d "/Applications/Emacs.app/Contents/MacOS/bin" ]; then
export PATH="/Applications/Emacs.app/Contents/MacOS/bin:$PATH"
alias emacs="emacs -nw" # Always launch "emacs" in terminal mode.
fi
```
The launcher script works by figuring out it's own absolute path on disk, even
if you are using a symlink to the script, it will resolve to correct real path.
This allows it to execute the main `Emacs.app/Contents/MacOS/Emacs` executable
via the correct path, so it can correctly pick up its dependencies from within
the …

feat(cli): add "emacs" CLI launcher script to Emacs.app/Conents/MacOS/bin

---

README.md
build-emacs-for-macos

This should let people on shared connections use the script if they have a
GitHub Personal Access Token available in the `GITHUB_TOKEN` environment
variable.
When making unauthenticated API requests to GitHub, requests are rate limited to
60 requests per hour based on source IP address. Hence on shared connections the
rate limit may easily be exceeded.
When making authenticated API requests to GitHub, up to 5000 requests per hour
is allowed, based on the authenticated user rather than source IP address.

feat(github): perform authenticated GitHub API requests when GITHUB_TOKEN env var is set

---

README.md
build-emacs-for-macos

- Allows makes builds less specific to the exact CPU it is built on, meaning if
it works one x86_64 Intel-based Mac, it should work on another, which was not
always the case before.
- Fixed issue where native-comp builds required the `gcc` homebrew package to be
installed.

fix: improve portability of builds

---

go.mod
go.sum
pkg/cask/live_check.go
pkg/cask/release_info.go
pkg/cask/update.go
pkg/cli/cask.go
pkg/cli/cli.go

This will be used by the jimeh/homebrew-emacs-builds brew tap repository in
combination with brew livecheck to automatically update cask formulas to the
latest nightly builds from the jimeh/emacs-builds repository.

feat(cask): add cask update command to manage cask formula

---

build-emacs-for-macos

It seems like Ruby's FileUtils.cp_r method especially was messing with some file
attributes, causing Emacs to print details about loading various elisp files on
startup. While when Emacs.app is copied into the output build directory using
"cp -a" instead of FileUtils.cp_r it does not exhibit this behavior.

refactor(embed): use cp, mv, and chmod shell commands instead of FileUtils

---

README.md
build-emacs-for-macos
pkg/sign/entitlements.go
pkg/sign/entitlements_test.go

Finally resolves #53. I've tested and confirmed the main issue was the lack of the `com.apple.security.cs.allow-dyld-environment-variables` signing entitlement. Coupled with improvements to the shared library relink paths, this should solve all issues around using native-comp in a self-contained app.
I've tested builds multiple times on a fresh macOS Big Sur VM, and have confirmed that native-comp works correctly both compiling new *.eln files, and later loading them when restarting Emacs.

fix(embed): relink shared libraries with @rpath instead of @executable_path

---

pkg/cask/update.go
pkg/plan/create.go
pkg/plan/create_test.go
pkg/plan/plan.go
pkg/release/channel.go
pkg/release/version.go
pkg/repository/repository.go
pkg/repository/repository_test.go
pkg/sanitize/string.go

Add support for naming release and builds accordingly when given a git ref for a
pretest (90 or above patch number) or release candidate ("-rcX" at the end of
the tag).

feat(plan): add support for pretest and release candidate builds

---

build-emacs-for-macos

This should allow mu4e to be loaded from the mu homebrew package, among
other homebrew packages that provides emacs site-lisp files.
Ref: https://github.com/jimeh/emacs-builds/issues/19

fix(site-lisp): add Homebrew's site-lisp directory to locallisppath

---

build-emacs-for-macos

When building Emacs 28.x the build script will attempt to patch configure.ac if
needed to support the latest version of libgccjit which renamed libgccjit.so to
libgccjit.dylib.
Fixes #72

fix(emacs-28): patch configure.ac to support latest libgccjit

---

build-emacs-for-macos

Based on #74 and tweaked slightly, this resolves the recent build issues with
the libgccjit v12 formula which has two directories that contain the .dylib
file.

fix(native-comp): compatibility with libgccjit 12 homebrew formula

---

Brewfile
Brewfile.ci

- Remove `curl` formula from `Brewfile` because it's a keg-only formula.
- Remove `python` from `Brewfile.ci`, as installing it on GitHub Action's
`macOS-11` fails right now. And using system Python to install `dmgbuild`
works fine.

fix(deps): remove needless deps

---

Gemfile
Makefile
build-emacs-for-macos

This is a near complete rewrite of the shared library embedder/bundler code. It
now correctly resolves shared libraries that link to other shared library files
in the same package via use of `@path`, which the libwebp package does
extensively between `libwebpdemux.2.dylib`, `libwebp.7.dylib` and
`libsharpyuv.0.dylib`.
These relative shared library links were not understood at all by the old
library bundler code.
The new replacement here fully understands and resolves all `@<something>`
placeholders in links to shared libraries. It operates in a two-step process
where it first walks down the three of all shared libraries that Emacs links to,
and all that they link to, etc. building a copy and relink plan.
In a second step it then executes the copy plan, followed by the relinking plan.
The …

fix(shared-libs): correctly resolve libwebp libraries

---

README.md
build-emacs-for-macos

Increases max open file limit to 10000 the same way as emacs-plus does. This is necessary for some packages like lsp-mode to work properly in some cases.
The limit is configurable via the `--fd-setsize` option. The default is `10000`. To disable this feature, use the `--no-fd-setsize` option, or provide `--fd-setsize` with a value that is less than `1024`.
Fixes #106

fix(compile-options): increase runtime max open files limit

---

build-emacs-for-macos

Changelog files from the `src` directory are however excluded. They're 6.7MB,
span 1985 to 2015, and are not very relevant for inclusion within the Emacs.app
bundle.
Resolves https://github.com/jimeh/emacs-builds/issues/40

fix(build/embed): include all Emacs C sources and related files in the Emacs.app bundle

---

build-emacs-for-macos

Because we bundle libgccjit and gcc libraries, as well as C sources into the
Emacs .app bundle itself, some extra setup is required during startup of emacs
to ensure that native compliation works, and C sources are found when needed.
Previously this was done by adding a custom site-start.el file to the Emacs.app
bundle, which was loaded at startup. This approach had some issues, namely that
when launching emacs with `-Q` or `--no-site-file`, the file was not loaded,
preventing native compilation from working.
Here we replace the site-start.el approach with a custom patch adding
macos-startup.el, which adds a hook to `after-pdump-load-hook`. This ensures
that the startup code is always run, and before any user configuration is
loaded.

feat(startup): replace bundled site-start.el approach with a custom source patch

---

README.md
build-emacs-for-macos

This allows users to easily apply custom patches from a file on disk, or from a
URL. It's particularly hady to quickly test out a changeset from a GitHub
commit/diff or elsewhere.

feat(options): add --patch option which accepts file path or URL

---

pkg/cli/plan.go
pkg/plan/create.go

This will allow planning numbered build variants for the same Emacs version.
For example, if Emacs-30.1 has been built and published already, and
changes/fixes in the build system require updating the 30.1 build, we can now
publish it as "Emacs-30.1-1".

feat(builder/plan): add build variant flag
